### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [IS1DespachoMotorizado/ISII-WORKSHOPS-DESPACHO_MOTORIZADO#1]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by caloja1014** [comment]
We will proceed to process the request, @NataliaMw  will be the assigned analyst, @jaimepizarr  will develop the solution, and
@caloja1014 will perform the tests.

**Comment by caloja1014** [comment]
We will proceed to process the request, @NataliaMw will be the assigned analyst, @jaimepizarr will develop the solution, and
@caloja1014 will perform the tests.

**Comment by jose598** [comment]
Thank you @caloja1014. I'm waiting for your response.

**Comment by jaimepizarr** [comment]
Hello to all, this is the solution to the issue
https://github.com/IS1DespachoMotorizado/ISII-WORKSHOPS-DESPACHO_MOTORIZADO/blob/6e9677983101da58bb8a4ad4d635c67f79c2a4a2/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L86-L91

**Comment by jose598** [comment]
@jaimepizarr I have an observation according to the code, when I mentioned this rules: if customer is married, is 30<age<60, then customer will receive $100 of discount because she/he receives discount for him/her and for his/her couple, no $50 like you did. Please change this on the analysis report as well and start working on the test plan. 


Thank you

**Comment by NataliaMw** [comment]
@jose598  Here is the new impact analysis with the changes
[Impact analysis.docx](https://github.com/IS1DespachoMotorizado/ISII-WORKSHOPS-DESPACHO_MOTORIZADO/files/7916814/Impact.analysis.docx)

**Comment by jaimepizarr** [comment]
@jose598 ok, I corrected that requirement.
https://github.com/IS1DespachoMotorizado/ISII-WORKSHOPS-DESPACHO_MOTORIZADO/blob/3e43ea613dc4e0c5bed711a8ebec2f12bc51e810/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L86-L91

**Comment by jose598** [comment]
Thank you @jaimepizarr and @NataliaMw, so I'll wait for your test plan.

**Comment by caloja1014** [comment]
@jose598  Hi, here is the test plan proposed.
[TestPlan.docx](https://github.com/IS1DespachoMotorizado/ISII-WORKSHOPS-DESPACHO_MOTORIZADO/files/7917481/TestPlan.docx)

**Comment by jose598** [comment]
@caloja1014 Thank you.
Everything sounds good.

**Comment by caloja1014** [comment]
@jose598 the solution has been completed and @jaimepizarr  will release the new software version for you.

**Comment by jaimepizarr** [comment]
@jose598 To use the solution, we need to clone the version from the branch IssueManagement. Once downloaded, the project has a main file called Main.java
From that file we can create new instances of CarInsurances and prove that the system works correctly by running this file.
The CarInsurance.java file has the class for the CarInsurance if you want to check it.
